modLoader = "kotlinforforge"
loaderVersion = "[47,)"
#issueTrackerURL = ""
license = "${license}"

[[mods]]
modId = "amethyst_applications"
version = "${version}"
displayName = "Amethyst Applications"
authors = "basil_squared"
description = '${description}'
#logoFile = ""

[[dependencies.amethyst_applications]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.amethyst_applications]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.amethyst_applications]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"
